name: lubricentro_mobile
description: Aplicación móvil para clientes y equipo del lubricentro.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  image_picker: ^1.2.3
  file_picker: ^11.0.3
  url_launcher: ^6.3.1
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gudex-logo.png
    - assets/catalogo-servicios.json
